language: cpp

os: linux  # Сборка на Linux

compiler:
  - gcc    # Тест с GCC
  - clang  # Тест с Clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
